### ISSUE TITLE
Missing bootstrap.js

### ISSUE THREAD

**Issue by diomededavid** [jmcooper/ng2f-bootstrap#1]
Can the bootstrap.js be added? It's missing when I download for the course.

**Comment by joeeames** [comment]
we don't use bootstrap.js in our course do we? I think we only need the css file correct?

**Comment by diomededavid** [comment]
For someone following the video. It took me an unnecessary amount time to find out where the js files were. I ended up downloading the files from the native Bootstrap package. 

Someone new to the course might not know that. Screenshot of the video and the bootstrap. I find the course to be very informative, but when the setup is different than the course instructs, it causes many to get frustrated and  stop following.

[Screen Shot 2019-04-23 at 8.37.04 AM.pdf](https://github.com/jmcooper/ng2f-bootstrap/files/3108368/Screen.Shot.2019-04-23.at.8.37.04.AM.pdf)
 
[Screen Shot 2019-04-23 at 8.47.10 AM.pdf](https://github.com/jmcooper/ng2f-bootstrap/files/3108399/Screen.Shot.2019-04-23.at.8.47.10.AM.pdf)
